### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by animeshsahu80**
HERE IS MY CONTRIBUTION

### CODE REVIEW

**Comment by JamezQ** [comment]
Is this commit basically just an advertisement for Mycroft on my readme?

**Comment by jegol** [comment]
Just seen the committer send a PR on another project (which caught my interest because it's pretty much dead at this point, and seeing activity was a surprise). Either the committer is a bot that pulls text from Wikipedia and other websites and inserts it into readme files, or they are a human who is overzealously copy-pasting from there. Either way, I've reported them/it.

**Comment by animeshsahu80** [comment]
I am not a bot.

Beep~bop

**Comment by jegol** [comment]
> I am not a bot. Beep~bop

(Sorry to JamezQ, this will be my last comment on this PR seeing as I'm not a contributor to this project, and I realise I'm being somewhat rude by commenting here.)

I stand by the "committer is a bot" assertion until I see evidence otherwise - what I just quoted is a cliche bot response. However, in the case that I'm wrong and you are actually human, I'll give you advice for committing to projects; don't copy and paste from elsewhere on the web, send a pull request for it and call that a contribution, because it's not. It's kind of spammy. If you want to contribute but you're not sure how, contribute code or project documentation for projects you care about. What you're doing now is unhelpful, and is likely to get you banned sooner or later.

**Comment by JamezQ** [comment]
@jegol I didn't find your comments rude at all, they were in fact helpful. It does indeed seem like a bot or spam. I think I will close this and report the user as well. 

The fact that you have seen this somewhere else helps to confirm that. Thanks!

**Comment by animeshsahu80** [comment]
hello guys, 
i am sorry for the inconvenience caused i am not a bot , someone from my college got access to my account password and did all these contributions because of which my account has been flagged and github is now asking me to close all of my pull request is there any thing that can be done from your side so that my account can be unflagged.
thanks.
and sorry again from my side

**Comment by animeshsahu80** [comment]
i know these are popular repositories and i don't want to mess with them. :)

**Pull request closed without merging**
